
import HizmetLayout from '@/components/HizmetLayout'
export const metadata = { title: 'Genetik Danışmanlık | Fetal Uzman' }
export default function Page() {
  return (
    <HizmetLayout title="Genetik Danışmanlık" subtitle="NIPT, amniyosentez ve prenatal genetik testler" icon="🧬" color="#3b82f6" category="Prenatal Genetik" sourceText="ACMG, ACOG, ESHG Guidelines">
      <section style={{marginBottom:'48px'}}><h2 style={{fontFamily:'Playfair Display,Georgia,serif',fontSize:'26px',fontWeight:800,color:'#0f0e2a',marginBottom:'20px',paddingBottom:'12px',borderBottom:'2px solid #f0ecf9'}}>Prenatal Genetik Danışmanlık</h2><div style={{fontSize:'16px',lineHeight:1.85,color:'#444'}}><p>Prenatal genetik danışmanlık; gebelik öncesinde veya sırasında genetik risk faktörlerinin değerlendirilmesi, uygun tarama/tanı testlerinin planlanması ve sonuçların yorumlanmasını kapsar.</p></div></section>
      <section style={{marginBottom:'48px'}}><h2 style={{fontFamily:'Playfair Display,Georgia,serif',fontSize:'26px',fontWeight:800,color:'#0f0e2a',marginBottom:'20px',paddingBottom:'12px',borderBottom:'2px solid #f0ecf9'}}>NIPT (Hücresiz Fetal DNA)</h2><div style={{fontSize:'16px',lineHeight:1.85,color:'#444'}}><p>Anne kanından alınan örnekte serbest fetal DNA analizi ile yapılır. 10. haftadan itibaren uygulanabilir.</p><ul><li><strong>Trizomi 21:</strong> Saptama oranı &gt;%99, yanlış pozitiflik ~%0.1</li><li><strong>Trizomi 18 ve 13:</strong> Yüksek saptama oranı</li><li><strong>Cinsiyet kromozom anomalileri:</strong> Değerlendirilebilir</li></ul><div style={{margin:'20px 0',padding:'16px 20px',borderRadius:'12px',background:'#fffbeb',border:'1.5px solid #fde68a'}}><div style={{fontWeight:700,color:'#92400e',marginBottom:'6px'}}>⚠️ Önemli</div><div style={{fontSize:'15px',color:'#92400e',lineHeight:1.7}}>NIPT bir tarama testidir — tanı koydurmaz. Pozitif sonuçta invaziv test (amniyosentez veya CVS) ile doğrulama gereklidir.</div></div></div></section>
      <section style={{marginBottom:'48px'}}><h2 style={{fontFamily:'Playfair Display,Georgia,serif',fontSize:'26px',fontWeight:800,color:'#0f0e2a',marginBottom:'20px',paddingBottom:'12px',borderBottom:'2px solid #f0ecf9'}}>İnvaziv Prenatal Testler</h2><div style={{fontSize:'16px',lineHeight:1.85,color:'#444'}}><table><thead><tr><th>Test</th><th>Zamanlama</th><th>İşlem</th><th>Kayıp Riski</th></tr></thead><tbody><tr><td>CVS</td><td>10–13. hafta</td><td>Plasenta biyopsisi</td><td>%0.5–1</td></tr><tr><td>Amniyosentez</td><td>15–20. hafta</td><td>Amniyotik sıvı</td><td>%0.1–0.3</td></tr></tbody></table></div></section>
      <div style={{marginTop:'60px',padding:'24px',background:'#f8f6ff',borderRadius:'16px',border:'1px solid #e8e4f8'}}><h4 style={{fontSize:'13px',fontWeight:800,color:'#888',letterSpacing:'1.5px',textTransform:'uppercase',marginBottom:'12px'}}>📚 Kaynaklar</h4><ul style={{margin:0,paddingLeft:'20px'}}><li style={{fontSize:'13px',color:'#666',marginBottom:'6px'}}>ACMG Practice Guideline: Prenatal/Preconception Expanded Carrier Screening (2021)</li><li style={{fontSize:'13px',color:'#666',marginBottom:'6px'}}>ACOG Practice Bulletin No. 226: Cell-Free DNA Screening (2020)</li><li style={{fontSize:'13px',color:'#666',marginBottom:'6px'}}>ESHG/ACMG: Recommendations for reporting secondary findings in clinical exome and genome sequencing (2023)</li></ul></div>
    </HizmetLayout>
  )
}
