import HizmetLayout from '@/components/HizmetLayout'
export const metadata = { title: 'Online Danışmanlık | Fetal Uzman' }
export default function Page() {
  return (
    <HizmetLayout title="Online Danışmanlık" subtitle="WhatsApp veya video görüşme ile uzman desteği" icon="💬" color="#ec4899" category="Danışmanlık" sourceText="fetaluzman.com">
      <section style={{marginBottom:'48px'}}><h2 style={{fontFamily:'Playfair Display,Georgia,serif',fontSize:'26px',fontWeight:800,color:'#0f0e2a',marginBottom:'20px',paddingBottom:'12px',borderBottom:'2px solid #f0ecf9'}}>Nasıl Çalışır?</h2><div style={{fontSize:'16px',lineHeight:1.85,color:'#444'}}><p>Randevunuzu WhatsApp veya web sitesi üzerinden alın. Gebelik bilgilerinizi ve sorularınızı paylaşın. Güvenli ödeme sonrası Google Meet üzerinden yüz yüze görüşme yapın.</p><table><thead><tr><th>Adım</th><th>Açıklama</th></tr></thead><tbody><tr><td>1️⃣ Randevu Al</td><td>WhatsApp veya web sitesi üzerinden uygun saati seçin</td></tr><tr><td>2️⃣ Bilgi Gönder</td><td>Gebelik haftası, sonuçlar ve sorularınızı paylaşın</td></tr><tr><td>3️⃣ Ödeme</td><td>Güvenli IBAN transferi ile ödemenizi tamamlayın</td></tr><tr><td>4️⃣ Görüşme</td><td>Google Meet ile 30–45 dk yüz yüze danışmanlık</td></tr></tbody></table></div></section>
      <section style={{marginBottom:'48px'}}><h2 style={{fontFamily:'Playfair Display,Georgia,serif',fontSize:'26px',fontWeight:800,color:'#0f0e2a',marginBottom:'20px',paddingBottom:'12px',borderBottom:'2px solid #f0ecf9'}}>Hangi Konularda Yardım Alabilirsiniz?</h2><div style={{fontSize:'16px',lineHeight:1.85,color:'#444'}}><ul><li>Ultrason ve tarama sonuçlarının yorumlanması</li><li>Yüksek risk sonuçları sonrası ne yapılmalı?</li><li>İkinci görüş (second opinion)</li><li>Gebelik komplikasyonları hakkında bilgi</li><li>Doğum planlaması ve hazırlık</li><li>Lohusalık dönemi soruları</li></ul><div style={{margin:'20px 0',padding:'16px 20px',borderRadius:'12px',background:'#fef2f2',border:'1.5px solid #fecaca'}}><div style={{fontWeight:700,color:'#991b1b',marginBottom:'6px'}}>🚨 Önemli Hatırlatma</div><div style={{fontSize:'15px',color:'#991b1b',lineHeight:1.7}}>Online danışmanlık, yüz yüze muayenenin yerini tutamaz. Acil durumlar için hemen hastaneye başvurun.</div></div></div></section>
      <div style={{textAlign:'center',marginTop:'40px'}}><a href="mailto:dr.mervenur@fetaluzman.com" style={{display:'inline-flex',alignItems:'center',gap:'10px',background:'#25D366',color:'#fff',fontWeight:700,fontSize:'16px',padding:'16px 36px',borderRadius:'30px',textDecoration:'none'}}> 📱 Hemen WhatsApp ile Yaz</a></div>
    </HizmetLayout>
  )
}
